version: '3'

services:
  api:
    build: .
    ports:
      - "10000:10000"
    env_file:
      - python_adk/.env
    volumes:
      - ./logs:/app/logs
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:10000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s 