services:
  # Frontend SPA
  - type: web
    name: phong-thuy-so-frontend
    env: static
    buildCommand: cd phong_thuy_so_frontend && npm install && npm run build
    staticPublishPath: ./phong_thuy_so_frontend/dist
    pullRequestPreviewsEnabled: true
    headers:
      - path: /*
        name: Cache-Control
        value: max-age=0, must-revalidate
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
    envVars:
      - key: VITE_API_BASE_URL
        value: https://api-phong-thuy-so.onrender.com
      - key: VITE_ADK_BASE_URL
        value: https://adk-backend.onrender.com
  
  # Backend API
  - type: web
    name: phong-thuy-so-api
    env: node
    buildCommand: npm install
    startCommand: node server.js
    healthCheckPath: /api/health
    envVars:
      - key: NODE_ENV
        value: production
      - key: MONGODB_URI
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: ADK_API_KEY
        sync: false
  
  # Landing Page: BatCucLinhSo
  - type: web
    name: bat-cuc-linh-so-landing
    env: static
    buildCommand: cd phong_thuy_so_frontend && npm install && npm run build:landing-bat-cuc
    staticPublishPath: ./phong_thuy_so_frontend/dist/landing/bat-cuc-linh-so
    domain: bat-cuc-linh-so.phongthuyso.vn

  # Node.js Backend
  - type: web
    name: phongthuybotbackend
    env: node
    region: singapore
    plan: starter
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: MONGODB_URI
        sync: false
      - key: PYTHON_ADK_URL
        value: https://phongthuybotadk.onrender.com
      - key: ADK_API_KEY
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: JWT_EXPIRE
        value: 30d
      - key: CLIENT_URL
        value: https://phongthuyso.onrender.com
      - key: GEMINI_API_KEY
        sync: false

  # Python ADK Service
  - type: web
    name: phongthuybotadk
    env: python
    region: singapore
    plan: starter
    buildCommand: pip install -r python_adk/requirements.txt
    startCommand: cd python_adk && python main.py
    envVars:
      - key: PORT
        value: 10000
      - key: HOST
        value: 0.0.0.0
      - key: LOG_LEVEL
        value: INFO
      - key: API_KEY
        sync: false
      - key: API_KEY_HEADER
        value: X-API-Key
      - key: GOOGLE_API_KEY
        sync: false
      - key: DEFAULT_MODEL
        value: gemini-pro
      - key: ROOT_AGENT_MODEL
        value: gemini-pro
      - key: BATCUCLINH_SO_AGENT_MODEL
        value: gemini-pro 